# Generated by Django 6.0 on 2026-04-03 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_category_slug_alter_news_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('baiterek', 'Байтерек'), ('qic', 'QIC')], max_length=20, verbose_name='Источник')),
                ('external_id', models.CharField(max_length=100, verbose_name='Внешний ID')),
                ('title', models.CharField(max_length=500, verbose_name='Заголовок')),
                ('url', models.URLField(max_length=1000, verbose_name='Ссылка')),
                ('image_url', models.URLField(blank=True, max_length=1000, verbose_name='URL изображения')),
                ('published_date', models.DateField(verbose_name='Дата публикации')),
                ('fetched_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Внешняя новость',
                'verbose_name_plural': 'Внешние новости',
                'ordering': ['-published_date'],
                'unique_together': {('source', 'external_id')},
            },
        ),
    ]
