# Generated by Django 6.0.4 on 2026-05-29 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_externalnews'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description_en',
            field=models.TextField(blank=True, verbose_name='Описание (английский)'),
        ),
        migrations.AddField(
            model_name='category',
            name='description_kk',
            field=models.TextField(blank=True, verbose_name='Описание (казахский)'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, verbose_name='Название (английский)'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_kk',
            field=models.CharField(blank=True, max_length=100, verbose_name='Название (казахский)'),
        ),
        migrations.AddField(
            model_name='externalnews',
            name='title_en',
            field=models.CharField(blank=True, max_length=500, verbose_name='Заголовок (английский)'),
        ),
        migrations.AddField(
            model_name='externalnews',
            name='title_kk',
            field=models.CharField(blank=True, max_length=500, verbose_name='Заголовок (казахский)'),
        ),
        migrations.AddField(
            model_name='news',
            name='content_en',
            field=models.TextField(blank=True, verbose_name='Содержание (английский)'),
        ),
        migrations.AddField(
            model_name='news',
            name='content_kk',
            field=models.TextField(blank=True, verbose_name='Содержание (казахский)'),
        ),
        migrations.AddField(
            model_name='news',
            name='excerpt_en',
            field=models.TextField(blank=True, max_length=500, verbose_name='Краткое описание (английский)'),
        ),
        migrations.AddField(
            model_name='news',
            name='excerpt_kk',
            field=models.TextField(blank=True, max_length=500, verbose_name='Краткое описание (казахский)'),
        ),
        migrations.AddField(
            model_name='news',
            name='meta_description_en',
            field=models.TextField(blank=True, max_length=500, verbose_name='SEO описание (английский)'),
        ),
        migrations.AddField(
            model_name='news',
            name='meta_description_kk',
            field=models.TextField(blank=True, max_length=500, verbose_name='SEO описание (казахский)'),
        ),
        migrations.AddField(
            model_name='news',
            name='meta_keywords_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='SEO ключевые слова (английский)'),
        ),
        migrations.AddField(
            model_name='news',
            name='meta_keywords_kk',
            field=models.CharField(blank=True, max_length=255, verbose_name='SEO ключевые слова (казахский)'),
        ),
        migrations.AddField(
            model_name='news',
            name='meta_title_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='SEO заголовок (английский)'),
        ),
        migrations.AddField(
            model_name='news',
            name='meta_title_kk',
            field=models.CharField(blank=True, max_length=255, verbose_name='SEO заголовок (казахский)'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='Заголовок (английский)'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_kk',
            field=models.CharField(blank=True, max_length=255, verbose_name='Заголовок (казахский)'),
        ),
    ]
