# Generated by Django 6.0 on 2025-12-24 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('projects', '0002_remove_project_sectors'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sector',
        ),
    ]
