# Generated by Django 6.0 on 2026-01-21 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_delete_sector'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название компании-партнера', max_length=255, verbose_name='Название компании')),
                ('logo', models.ImageField(help_text='Логотип компании-партнера', upload_to='partners/logos/', verbose_name='Логотип')),
                ('website', models.URLField(blank=True, help_text='Ссылка на сайт партнера (необязательно)', verbose_name='Сайт')),
                ('is_active', models.BooleanField(default=True, help_text='Отображать партнера на сайте', verbose_name='Активен')),
                ('order', models.PositiveIntegerField(default=0, help_text='Порядок отображения (меньше - раньше)', verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Партнер',
                'verbose_name_plural': 'Партнеры',
                'ordering': ['order', 'name'],
                'indexes': [models.Index(fields=['is_active', 'order'], name='core_partne_is_acti_61f726_idx')],
            },
        ),
    ]
