# Generated by Django 6.0 on 2026-05-04 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='partner',
            name='core_partne_is_acti_61f726_idx',
        ),
        migrations.DeleteModel(
            name='Partner',
        ),
    ]
