# Generated by Django 6.0 on 2026-05-04 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_drop_partner'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('middle_name', models.CharField(blank=True, max_length=100, verbose_name='Отчество')),
                ('position', models.CharField(max_length=255, verbose_name='Должность')),
                ('group', models.CharField(choices=[('management', 'Руководство'), ('board', 'Совет директоров')], default='management', max_length=20, verbose_name='Группа')),
                ('citizenship', models.CharField(default='Республика Казахстан', max_length=100, verbose_name='Гражданство')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Член команды',
                'verbose_name_plural': 'Команда',
                'ordering': ['group', 'order', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='TeamMemberBioSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Например: Сведения о трудовой деятельности', max_length=200, verbose_name='Заголовок')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bio_sections', to='core.teammember')),
            ],
            options={
                'verbose_name': 'Раздел биографии',
                'verbose_name_plural': 'Разделы биографии',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TeamMemberBioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.teammemberbiosection')),
            ],
            options={
                'verbose_name': 'Пункт биографии',
                'verbose_name_plural': 'Пункты биографии',
                'ordering': ['order'],
            },
        ),
    ]
