# Generated by Django 6.0 on 2026-05-04 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_team_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='team/', verbose_name='Фото'),
        ),
    ]
