# Generated by Django 6.0.4 on 2026-05-29 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_team_member_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='citizenship_en',
            field=models.CharField(blank=True, max_length=100, verbose_name='Гражданство (английский)'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='citizenship_kk',
            field=models.CharField(blank=True, max_length=100, verbose_name='Гражданство (казахский)'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='first_name_en',
            field=models.CharField(blank=True, max_length=100, verbose_name='Имя (английский)'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='first_name_kk',
            field=models.CharField(blank=True, max_length=100, verbose_name='Имя (казахский)'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='last_name_en',
            field=models.CharField(blank=True, max_length=100, verbose_name='Фамилия (английский)'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='last_name_kk',
            field=models.CharField(blank=True, max_length=100, verbose_name='Фамилия (казахский)'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='middle_name_en',
            field=models.CharField(blank=True, max_length=100, verbose_name='Отчество (английский)'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='middle_name_kk',
            field=models.CharField(blank=True, max_length=100, verbose_name='Отчество (казахский)'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='position_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='Должность (английский)'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='position_kk',
            field=models.CharField(blank=True, max_length=255, verbose_name='Должность (казахский)'),
        ),
        migrations.AddField(
            model_name='teammemberbioitem',
            name='text_en',
            field=models.TextField(blank=True, verbose_name='Текст (английский)'),
        ),
        migrations.AddField(
            model_name='teammemberbioitem',
            name='text_kk',
            field=models.TextField(blank=True, verbose_name='Текст (казахский)'),
        ),
        migrations.AddField(
            model_name='teammemberbiosection',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='Заголовок (английский)'),
        ),
        migrations.AddField(
            model_name='teammemberbiosection',
            name='title_kk',
            field=models.CharField(blank=True, max_length=200, verbose_name='Заголовок (казахский)'),
        ),
    ]
