# Generated by Django 6.0 on 2025-12-24 15:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='URL слаг')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Иконка (FontAwesome класс)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Категория проекта',
                'verbose_name_plural': 'Категории проектов',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название проекта')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='URL слаг')),
                ('short_description', models.TextField(max_length=500, verbose_name='Краткое описание')),
                ('description', models.TextField(verbose_name='Полное описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/%Y/%m/%d/', verbose_name='Главное изображение')),
                ('gallery', models.JSONField(blank=True, default=list, verbose_name='Галерея изображений (URLs)')),
                ('investment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Сумма инвестиций')),
                ('currency', models.CharField(default='KZT', max_length=3, verbose_name='Валюта')),
                ('expected_roi', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Ожидаемая доходность (%)')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Дата начала')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('status', models.CharField(choices=[('planning', 'Планирование'), ('active', 'Активный'), ('completed', 'Завершен'), ('suspended', 'Приостановлен')], default='planning', max_length=20, verbose_name='Статус проекта')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Избранный проект')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Местоположение (город/регион)')),
                ('country', models.CharField(default='Kazakhstan', max_length=100, verbose_name='Страна')),
                ('partners', models.TextField(blank=True, verbose_name='Партнеры/инвесторы')),
                ('meta_title', models.CharField(blank=True, max_length=255, verbose_name='SEO заголовок')),
                ('meta_description', models.TextField(blank=True, max_length=500, verbose_name='SEO описание')),
                ('meta_keywords', models.CharField(blank=True, max_length=255, verbose_name='SEO ключевые слова')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Количество просмотров')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликовано')),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('sectors', models.ManyToManyField(blank=True, related_name='projects', to='core.sector', verbose_name='Отраслевые секторы')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='projects.projectcategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'ordering': ['-published_date'],
                'indexes': [models.Index(fields=['-published_date'], name='projects_pr_publish_5d19b2_idx'), models.Index(fields=['slug'], name='projects_pr_slug_042165_idx'), models.Index(fields=['status'], name='projects_pr_status_f023cb_idx')],
            },
        ),
    ]
