# Generated by Django 6.0 on 2025-12-24 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='sectors',
        ),
    ]
