# Generated by Django 6.0 on 2025-12-24 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_remove_project_sectors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='gallery',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Галерея изображений (URLs)'),
        ),
    ]
