# Generated by Django 6.0.4 on 2026-05-29 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='country_en',
            field=models.CharField(blank=True, max_length=100, verbose_name='Страна (английский)'),
        ),
        migrations.AddField(
            model_name='project',
            name='country_kk',
            field=models.CharField(blank=True, max_length=100, verbose_name='Страна (казахский)'),
        ),
        migrations.AddField(
            model_name='project',
            name='description_en',
            field=models.TextField(blank=True, verbose_name='Полное описание (английский)'),
        ),
        migrations.AddField(
            model_name='project',
            name='description_kk',
            field=models.TextField(blank=True, verbose_name='Полное описание (казахский)'),
        ),
        migrations.AddField(
            model_name='project',
            name='location_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='Местоположение (английский)'),
        ),
        migrations.AddField(
            model_name='project',
            name='location_kk',
            field=models.CharField(blank=True, max_length=255, verbose_name='Местоположение (казахский)'),
        ),
        migrations.AddField(
            model_name='project',
            name='meta_description_en',
            field=models.TextField(blank=True, max_length=500, verbose_name='SEO описание (английский)'),
        ),
        migrations.AddField(
            model_name='project',
            name='meta_description_kk',
            field=models.TextField(blank=True, max_length=500, verbose_name='SEO описание (казахский)'),
        ),
        migrations.AddField(
            model_name='project',
            name='meta_keywords_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='SEO ключевые слова (английский)'),
        ),
        migrations.AddField(
            model_name='project',
            name='meta_keywords_kk',
            field=models.CharField(blank=True, max_length=255, verbose_name='SEO ключевые слова (казахский)'),
        ),
        migrations.AddField(
            model_name='project',
            name='meta_title_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='SEO заголовок (английский)'),
        ),
        migrations.AddField(
            model_name='project',
            name='meta_title_kk',
            field=models.CharField(blank=True, max_length=255, verbose_name='SEO заголовок (казахский)'),
        ),
        migrations.AddField(
            model_name='project',
            name='partners_en',
            field=models.TextField(blank=True, verbose_name='Партнеры/инвесторы (английский)'),
        ),
        migrations.AddField(
            model_name='project',
            name='partners_kk',
            field=models.TextField(blank=True, verbose_name='Партнеры/инвесторы (казахский)'),
        ),
        migrations.AddField(
            model_name='project',
            name='short_description_en',
            field=models.TextField(blank=True, max_length=500, verbose_name='Краткое описание (английский)'),
        ),
        migrations.AddField(
            model_name='project',
            name='short_description_kk',
            field=models.TextField(blank=True, max_length=500, verbose_name='Краткое описание (казахский)'),
        ),
        migrations.AddField(
            model_name='project',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='Название проекта (английский)'),
        ),
        migrations.AddField(
            model_name='project',
            name='title_kk',
            field=models.CharField(blank=True, max_length=255, verbose_name='Название проекта (казахский)'),
        ),
        migrations.AddField(
            model_name='projectcategory',
            name='description_en',
            field=models.TextField(blank=True, verbose_name='Описание (английский)'),
        ),
        migrations.AddField(
            model_name='projectcategory',
            name='description_kk',
            field=models.TextField(blank=True, verbose_name='Описание (казахский)'),
        ),
        migrations.AddField(
            model_name='projectcategory',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, verbose_name='Название (английский)'),
        ),
        migrations.AddField(
            model_name='projectcategory',
            name='name_kk',
            field=models.CharField(blank=True, max_length=100, verbose_name='Название (казахский)'),
        ),
    ]
