# Generated by Django 6.0 on 2026-01-23 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='Слаг')),
                ('sector', models.CharField(max_length=255, verbose_name='Сектор')),
                ('subtitle', models.CharField(max_length=500, verbose_name='Подзаголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('fund_type', models.CharField(max_length=255, verbose_name='Тип фонда')),
                ('target_size', models.CharField(max_length=255, verbose_name='Целевой размер')),
                ('registration_date', models.DateField(verbose_name='Дата регистрации')),
                ('items_title', models.CharField(default='Цели фонда', max_length=255, verbose_name='Заголовок списка элементов')),
                ('is_secondary', models.BooleanField(default=False, help_text='Использовать ли вторичную цветовую схему', verbose_name='Вторичный стиль')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Фонд',
                'verbose_name_plural': 'Фонды',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FundItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(help_text='Например: fas fa-chart-line', max_length=100, verbose_name='Иконка (FontAwesome)')),
                ('text', models.CharField(max_length=500, verbose_name='Текст')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='holdings.fund')),
            ],
            options={
                'verbose_name': 'Элемент фонда',
                'verbose_name_plural': 'Элементы фонда',
                'ordering': ['order'],
            },
        ),
    ]
