# Generated by Django 6.0 on 2026-01-23 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('holdings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fund',
            name='sector',
        ),
        migrations.RemoveField(
            model_name='fund',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='fund',
            name='subtitle',
        ),
    ]
