# Generated by Django 6.0 on 2026-05-04 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holdings', '0002_remove_fund_sector_remove_fund_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fund',
            name='description',
        ),
        migrations.RemoveField(
            model_name='fund',
            name='is_secondary',
        ),
        migrations.RemoveField(
            model_name='fund',
            name='items_title',
        ),
        migrations.AddField(
            model_name='fund',
            name='badge',
            field=models.CharField(default='', help_text='Например: Открытый фонд', max_length=100, verbose_name='Бейдж'),
        ),
        migrations.AddField(
            model_name='fund',
            name='is_dark',
            field=models.BooleanField(default=False, verbose_name='Тёмная карточка'),
        ),
        migrations.AddField(
            model_name='fund',
            name='lifespan',
            field=models.CharField(default='', help_text='Например: 10 лет', max_length=50, verbose_name='Срок жизни'),
        ),
        migrations.AlterField(
            model_name='fund',
            name='target_size',
            field=models.CharField(help_text='Например: $1 млрд', max_length=100, verbose_name='Целевой размер'),
        ),
        migrations.CreateModel(
            name='FundGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='Цель')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='holdings.fund')),
            ],
            options={
                'verbose_name': 'Цель фонда',
                'verbose_name_plural': 'Цели фонда',
                'ordering': ['order'],
            },
        ),
        migrations.DeleteModel(
            name='FundItem',
        ),
    ]
