# Generated by Django 6.0.4 on 2026-05-29 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holdings', '0003_restructure_fund'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='badge_en',
            field=models.CharField(blank=True, max_length=100, verbose_name='Бейдж (английский)'),
        ),
        migrations.AddField(
            model_name='fund',
            name='badge_kk',
            field=models.CharField(blank=True, max_length=100, verbose_name='Бейдж (казахский)'),
        ),
        migrations.AddField(
            model_name='fund',
            name='fund_type_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='Тип фонда (английский)'),
        ),
        migrations.AddField(
            model_name='fund',
            name='fund_type_kk',
            field=models.CharField(blank=True, max_length=255, verbose_name='Тип фонда (казахский)'),
        ),
        migrations.AddField(
            model_name='fund',
            name='lifespan_en',
            field=models.CharField(blank=True, max_length=50, verbose_name='Срок жизни (английский)'),
        ),
        migrations.AddField(
            model_name='fund',
            name='lifespan_kk',
            field=models.CharField(blank=True, max_length=50, verbose_name='Срок жизни (казахский)'),
        ),
        migrations.AddField(
            model_name='fund',
            name='name_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='Название (английский)'),
        ),
        migrations.AddField(
            model_name='fund',
            name='name_kk',
            field=models.CharField(blank=True, max_length=255, verbose_name='Название (казахский)'),
        ),
        migrations.AddField(
            model_name='fund',
            name='target_size_en',
            field=models.CharField(blank=True, max_length=100, verbose_name='Целевой размер (английский)'),
        ),
        migrations.AddField(
            model_name='fund',
            name='target_size_kk',
            field=models.CharField(blank=True, max_length=100, verbose_name='Целевой размер (казахский)'),
        ),
        migrations.AddField(
            model_name='fundgoal',
            name='text_en',
            field=models.CharField(blank=True, max_length=500, verbose_name='Цель (английский)'),
        ),
        migrations.AddField(
            model_name='fundgoal',
            name='text_kk',
            field=models.CharField(blank=True, max_length=500, verbose_name='Цель (казахский)'),
        ),
    ]
