# Generated by Django 6.0 on 2025-12-20 07:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='имя')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('phone', models.CharField(max_length=20, verbose_name='телефон')),
                ('subject', models.CharField(choices=[('investment', 'Инвестиционные проекты'), ('consulting', 'Консультации'), ('partnership', 'Сотрудничество'), ('other', 'Другое')], default='other', max_length=20, verbose_name='тема')),
                ('message', models.TextField(verbose_name='сообщение')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес')),
                ('user_agent', models.CharField(blank=True, max_length=500, verbose_name='User Agent')),
                ('is_read', models.BooleanField(default=False, verbose_name='прочитано')),
                ('is_replied', models.BooleanField(default=False, verbose_name='ответ отправлен')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата создания')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='дата прочтения')),
            ],
            options={
                'verbose_name': 'сообщение',
                'verbose_name_plural': 'сообщения',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='contacts_co_created_c45a93_idx'), models.Index(fields=['is_read'], name='contacts_co_is_read_ac8ea4_idx'), models.Index(fields=['email'], name='contacts_co_email_c0952a_idx')],
            },
        ),
    ]
