# Generated by Django 6.0 on 2026-01-06 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100, verbose_name='город')),
                ('address', models.CharField(max_length=255, verbose_name='адрес')),
                ('phone', models.CharField(max_length=50, verbose_name='телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('working_hours', models.CharField(default='Пн-Пт 9:00-18:00', max_length=200, verbose_name='режим работы')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Например: 51.169392', max_digits=9, null=True, verbose_name='широта')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Например: 71.449074', max_digits=9, null=True, verbose_name='долгота')),
                ('is_main', models.BooleanField(default=False, verbose_name='главный офис')),
                ('is_active', models.BooleanField(default=True, verbose_name='активен')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата обновления')),
            ],
            options={
                'verbose_name': 'офис',
                'verbose_name_plural': 'офисы',
                'ordering': ['order', 'city'],
            },
        ),
    ]
