# Generated by Django 6.0 on 2026-01-16 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_office'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='facebook',
            field=models.URLField(blank=True, help_text='Ссылка на страницу Facebook', verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='office',
            name='instagram',
            field=models.URLField(blank=True, help_text='Ссылка на профиль Instagram', verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='office',
            name='linkedin',
            field=models.URLField(blank=True, help_text='Ссылка на профиль LinkedIn', verbose_name='LinkedIn'),
        ),
        migrations.AddField(
            model_name='office',
            name='telegram',
            field=models.CharField(blank=True, help_text='Username или ссылка на канал', max_length=100, verbose_name='Telegram'),
        ),
        migrations.AddField(
            model_name='office',
            name='tiktok',
            field=models.URLField(blank=True, help_text='Ссылка на профиль TikTok', verbose_name='TikTok'),
        ),
        migrations.AddField(
            model_name='office',
            name='twitter',
            field=models.URLField(blank=True, help_text='Ссылка на профиль Twitter/X', verbose_name='Twitter/X'),
        ),
        migrations.AddField(
            model_name='office',
            name='whatsapp',
            field=models.CharField(blank=True, help_text='Номер телефона для WhatsApp', max_length=20, verbose_name='WhatsApp'),
        ),
        migrations.AddField(
            model_name='office',
            name='youtube',
            field=models.URLField(blank=True, help_text='Ссылка на канал YouTube', verbose_name='YouTube'),
        ),
    ]
