# Generated by Django 6.0 on 2026-03-05 05:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_office_facebook_office_instagram_office_linkedin_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('read', 'Прочитано'), ('in_progress', 'В обработке'), ('replied', 'Ответ отправлен'), ('cancelled', 'Отменена')], default='new', max_length=20, verbose_name='статус'),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_messages', to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
        migrations.AddIndex(
            model_name='contactmessage',
            index=models.Index(fields=['user', '-created_at'], name='contacts_co_user_id_52a9ac_idx'),
        ),
        migrations.AddIndex(
            model_name='contactmessage',
            index=models.Index(fields=['status'], name='contacts_co_status_e4ac66_idx'),
        ),
    ]
