# Generated by Django 6.0.4 on 2026-05-29 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_add_user_and_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='address_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='адрес (английский)'),
        ),
        migrations.AddField(
            model_name='office',
            name='address_kk',
            field=models.CharField(blank=True, max_length=255, verbose_name='адрес (казахский)'),
        ),
        migrations.AddField(
            model_name='office',
            name='city_en',
            field=models.CharField(blank=True, max_length=100, verbose_name='город (английский)'),
        ),
        migrations.AddField(
            model_name='office',
            name='city_kk',
            field=models.CharField(blank=True, max_length=100, verbose_name='город (казахский)'),
        ),
        migrations.AddField(
            model_name='office',
            name='working_hours_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='режим работы (английский)'),
        ),
        migrations.AddField(
            model_name='office',
            name='working_hours_kk',
            field=models.CharField(blank=True, max_length=200, verbose_name='режим работы (казахский)'),
        ),
    ]
